// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcoyodvdcflgywhuawhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjb3lvZHZkY2ZsZ3l3aHVhd2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODUwMTEsImV4cCI6MjA2MzY2MTAxMX0.kH9CTOab3wpDahtSdbcOJA6PM6etPhDyDn7hZ_2Zv9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);